### PR TITLE
Huge update

### PR DESCRIPTION
**Pull request by Wired203**
Healers will attack when they select a mob, otherwise they will heal as normal.
 Changed tank detection routine to make it less spammy for targeting.
 Healers Rejoice, you can now pull mobs and attack when using a grind profile. This wasn't available in the past with Default Combat.
 Rest is fixed to exit in background again, sendkeys no longer works for background
 Tank selection is working as it should. If companion is out he will be tank. If no companion and no tank you will become tank. F12 is fully tested and re-written to work correctly. F12 will set tank if a friendly target is selected. To clear the selection just target either a unfriendly or nothing or current f12 tank and hit f12. Bot will then go back to auto Tank selection.
 Added scavenging and bio to corpses.
 Cryo came up with the code for Stims and XP boosts when under 65.
 Dispel is tested but we have very few debuff names in the list. List is found under Helpers/Extensions.cs Public Static Debuff (If anyone has any to add let me know)
 Aoe heals are working, they used melee.dist for their distance checks to fire which was .8f and was changed to it's own float value and 1.2f - Thanks Tiniq
 Removed health logging as it was causing errors/issues
 Thanks to Alltrueist as he has updated quite a few of the routines for healing which were very out of date due to the healing not working for so long.

### CODE REVIEW

**Comment by aevitas** [comment]
This is going to be quite a bit of code to review. @Wired203 Can you resolve the conflicts this currently has with master so we can verify it compiles? Thanks!

**Comment by Wired203** [comment]
I couldn't figure out the newline issue honestly,  It does compile but for the life of me searching I couldn't identify what causes that with Git's checker. Date: Mon, 11 Apr 2016 05:27:20 -0700From: notifications@github.comTo: BuddyWing.DefaultCombat@noreply.github.comCC: wired203@hotmail.comSubject: Re: [BosslandGmbH/BuddyWing.DefaultCombat] Huge update (#24)This is going to be quite a bit of code to review. @Wired203 Can you resolve the conflicts this currently has with master so we can verify it compiles? Thanks!

**Comment by aevitas** [comment]
Managed to get anywhere with this? Looking forward to the improvements it brings! :)

**Comment by Wired203** [comment]
Thing is it compiles just fine,  looking up the newline with appveyor gives no insight as to why it throws it.  Some people have had it plague them with no fix.  Any ideas?

**Comment by Wired203** [comment]
Check this information out,  http://help.appveyor.com/discussions/problems/3954-test-failure-cause-by-different-newlines  

Everything compiles but app veyor is being doofy.

**Comment by aevitas** [comment]
@Wired203 There are conflicts: https://github.com/BosslandGmbH/BuddyWing.DefaultCombat/commit/ca824f8ff0670d7da1c8e1acd8af9d54613bc527

You should be able to resolve those by merging the master branch into yours and then resolving the conflicts manually. AppVeyor is simply signalling it can not build a PR that can't be merged (as it merges the branch as if it were merged to master already)

**Pull request merged**
